year = int(input("Enter a year: "))
match year % 12:
    case 0: print("monkey")
    case 1: print("rooster")
    case 2: print("dog")
    case 3: print("pig")
    case 4: print("rat")
    case 5: print("ox")
    case 6: print("tiger")
    case 7: print("rabbit")
    case 8: print("dragon")
    case 9: print("snake")
    case 10: print("horse")
    case 11: print("sheep")
